// File generated by FlutterFire CLI / Cipher-X Platform Architecture.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCipherXDevWebPlaceholderKey001',
    appId: '1:102938475601:web:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '102938475601',
    projectId: 'cipher-x-dev',
    authDomain: 'cipher-x-dev.firebaseapp.com',
    storageBucket: 'cipher-x-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCipherXDevAndroidPlaceholderKey01',
    appId: '1:102938475601:android:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '102938475601',
    projectId: 'cipher-x-dev',
    storageBucket: 'cipher-x-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCipherXDevIOSPlaceholderKey0001',
    appId: '1:102938475601:ios:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '102938475601',
    projectId: 'cipher-x-dev',
    storageBucket: 'cipher-x-dev.appspot.com',
    iosBundleId: 'com.decrypters.cipherX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCipherXDevMacOSPlaceholderKey00',
    appId: '1:102938475601:ios:a1b2c3d4e5f6g7h8i9j0',
    messagingSenderId: '102938475601',
    projectId: 'cipher-x-dev',
    storageBucket: 'cipher-x-dev.appspot.com',
    iosBundleId: 'com.decrypters.cipherX',
  );
}
